export enum AnimalType {
  Cat = "cat",
  Dog = "dog",
}

export enum Gender {
  Male = "male",
  Female = "female",
}

export const names = {
  [AnimalType.Cat]: {
    [Gender.Female]: [
      "Luna",
      "Bella",
      "Molly",
      "Daisy",
      "Zoe",
      "Cleo",
      "Sasha",
      "Nala",
      "Misty",
      "Tilly",
      "Ginger",
      "Penny",
      "Ruby",
      "Willow",
      "Olive",
      "Minnie",
      "Hazel",
      "Ivy",
      "Phoebe",
      "Lily",
    ],
    [Gender.Male]: [
      "Max",
      "Oliver",
      "Charlie",
      "Leo",
      "Milo",
      "Simba",
      "Oscar",
      "Jack",
      "Felix",
      "Jasper",
      "George",
      "Sammy",
      "Toby",
      "Buddy",
      "Gizmo",
      "Henry",
      "Dexter",
      "Louie",
      "Rocky",
      "Alfie",
    ],
  },
  [AnimalType.Dog]: {
    [Gender.Female]: [
      "Bella",
      "Lucy",
      "Daisy",
      "Molly",
      "Lola",
      "Sadie",
      "Maggie",
      "Chloe",
      "Bailey",
      "Sophie",
      "Luna",
      "Zoe",
      "Stella",
      "Roxy",
      "Penny",
      "Gracie",
      "Ruby",
      "Abby",
      "Lily",
      "Coco",
    ],
    [Gender.Male]: [
      "Max",
      "Charlie",
      "Buddy",
      "Cooper",
      "Rocky",
      "Jack",
      "Bear",
      "Duke",
      "Toby",
      "Oliver",
      "Bentley",
      "Milo",
      "Teddy",
      "Winston",
      "Louie",
      "Riley",
      "Murphy",
      "Leo",
      "Bailey",
      "Gus",
    ],
  },
};
