name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Deploy Lambda function
        run: |
          aws lambda create-function \
            --function-name my-lambda-function \
            --runtime nodejs18.x \
            --handler index.handler \
            --zip-file fileb://./path/to/lambda.zip \
            --region eu-west-1
